In [1]:
# Set-up Python libraries - you need to run this but you don't need to change it
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import pandas as pd
import seaborn as sns
sns.set_theme(style='white')
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
sm = pd.read_csv('DummyEg1.csv')
sm

   health           smoke
0       3  Current smoker
1       5    Never smoked
2       4    Never smoked
3       3    Never smoked
4       4       Ex smoker
5       4    Never smoked
6       2    Never smoked
7       2       Ex smoker
8       3    Never smoked
9       4  Current smoker

In [3]:
sm['Never smoked']=0
sm.loc[(sm.smoke=='Never smoked'),'Never smoked']=1
sm['Ex smoker']=0
sm.loc[(sm.smoke=='Ex smoker'),'Ex smoker']=1
sm

   health           smoke  Never smoked  Ex smoker
0       3  Current smoker             0          0
1       5    Never smoked             1          0
2       4    Never smoked             1          0
3       3    Never smoked             1          0
4       4       Ex smoker             0          1
5       4    Never smoked             1          0
6       2    Never smoked             1          0
7       2       Ex smoker             0          1
8       3    Never smoked             1          0
9       4  Current smoker             0          0